blank_issues_enabled: false
contact_links:
  - name: User Story Template
    url: https://github.com/MaireadKelly/PP4/issues/new?template=user_story.md
    about: "Use this template for adding new user stories."
